### ISSUE TITLE
[Enhancement] Add sound interpolation options

### ISSUE THREAD

**Issue by NineKain** [Arisotura/melonDS#1139]
They should smooth out those... crispy highs on the DS, playing some games (classic Dragon Quests) breaks my ears.

**Comment by blayney** [comment]
I think the effect is caused by a combination of no-dither 10 bit output from the mixer, and the downsampling of each channel of the mixer (which can be fed by PCM up to 24 bit) down to 10 bit. It's possible that you could move the artifacts up out of the audible range by supersampling the output of the mixer, which could be done in real time at some cost. The mixer on the NDS was apparently outputing at 10 bit, ~33KHz so you effectively have a cuttoff frequency of around 14 or 15KHz, depending on the ailiasing filter. The filter could be contributing it's own frequency response, but that's unlikely. You could also trade away the artifacts for a higher noise floor with some kind of real time dither system, but at 10 bit that noise floor is going to be very audible.

**Comment by Arisotura** [comment]
melonDS outputs 16-bit samples, without downgrading them to 10-bit.

anyway, some of the DS crustiness is indeed caused by the lack of audio interpolation, though that depends on how good the game's audio samples are.

latest revision of melonDS has an option for audio interpolation, check that out.
