### ISSUE TITLE
Video Settings Page Broken

### ISSUE THREAD

**Issue by theofficialgman** [Arisotura/melonDS#1224]
Making changes under the video settings page does not stay/save on close.

Opening this dialog results in this error in terminal
```
QObject::connect: No such signal QButtonGroup::idClicked(int)

QObject::connect:  (receiver name: 'VideoSettingsDialog')

```
specifically the sofware/opengl toggle does not work
other settings work fine
tested on master branch commit 35e93d5fec12e0b8043737482c86e4c7287762e7
manually changing settings through the ini file does work and reports correctly in the video settings dialog

**Comment by theofficialgman** [comment]
it seems like this line was changed with the QT6 additional build option. maybe it hasn't been working since then? https://github.com/Arisotura/melonDS/pull/865/files
note I'm building on qt5.12

**Comment by RayyanAnsari** [comment]
I am on Fedora 34 x86-64, and the Video Settings dialog works normally. I don't get the error and it saves the setting.
This is because you are using Ubuntu Bionic, which ships an old version of Qt.
The `QButtonGroup::idClicked`signal  was added in Qt 5.15.
Relevant code : https://github.com/Arisotura/melonDS/blob/35e93d5fec12e0b8043737482c86e4c7287762e7/src/frontend/qt_sdl/VideoSettingsDialog.cpp#L50

That idClicked should be changed to something that works with old Qt versions because of Ubuntu's outdated Qt packages.

**Comment by theofficialgman** [comment]
yeah bionic ships qt 5.9.5, focal ships qt 5.12
so this commit basically just made it incompatible with most linux users
I already built qt5.12 for other compatibility reasons to use here

**Comment by theofficialgman** [comment]
also do note that other places still use `buttonClicked` in the melonDS code... so if that doesn't work anymore in QT6 then you have more issues to workout

**Comment by theofficialgman** [comment]
looks to me like buttonclicked is still in QT6, so my suggestion is to change that back to line back to buttonclicked to maintain compatibilty with bionic, focal, and other ubuntu and debian versions

**Comment by RayyanAnsari** [comment]
https://doc.qt.io/qt-6/qbuttongroup.html#buttonToggled
It is in Qt 6, so I'll check with the rest of the team as to why this was changed,

**Comment by nadiaholmquist** [comment]
https://github.com/Arisotura/melonDS/compare/35e93d5fec12...1471c73ea698 this should hopefully fix it.

Debian and Ubuntu are such a pain in the ass for software development, always holding you back from using features that were introduced even years back because of some false promise about stability while they regularly break things by thinking they can take the role of upstream and patching all the software they ship...

**Comment by theofficialgman** [comment]
fixed enough
