### ISSUE TITLE
melonDS for macOS 10.13?

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#1444]
Hello I downloaded melonDS.app (0.9.4) for the first time as a new user and wanted to open the app on macOS 10.13, but it does not work.

Is there an overview which operating system version melonDS 0.9.4 supports? Which melonDS version still supports macOS 10.13?

**Comment by RayyanAnsari** [comment]
melonDS requires macOS 10.15+ if I remember correctly.

**Comment by xfrisakbaeun** [comment]
> melonDS requires macOS 10.15+ if I remember correctly.

Thanks for the answer. Since which melonDS version is macOS 10.15+ required? 

Would it be possible to support macOS 10.13 in the next version (0.9.5)?

**Comment by nadiaholmquist** [comment]
melonDS relies on features only by default present in 10.15 and up, this can (and used to) be worked around to support 10.14, but since it's now EOL and GitHub Actions no longer supports it meaning we can't easily make builds for it, we decided to drop support.

**Comment by xfrisakbaeun** [comment]
@nadiaholmquist 

I can't build it because I only run executable software (.app). Can you support macOS 10.13 afterwards? I don't use any github actions or anything like that and only download the official release version that comes out every few months.

It looks like melonDS 0.9.4 supports Windows version, starting from Windows Vista+.

**Comment by nadiaholmquist** [comment]
Compared to Windows it's sort of a pain to deal with older versions of macOS for cross-platform projects like melonDS. Homebrew, the primary way most people install the dependencies needed (rather unnecessarily as far as I can tell) goes out of its way to build packages targeting the macOS version you are running, rather than the one targeted by the project they're packaging itself. This means they won't work on any older version.

The most feasible way to make a 10.13 build would be for me to install it in a virtual machine, build all the dependencies from source and then build melonDS, it's not really difficult for me to do, but it's quite a time sink to support an OS that is no longer officially supported by Apple with a very small remaining user base.

**Comment by xfrisakbaeun** [comment]
> Compared to Windows it's sort of a pain to deal with older versions of macOS for cross-platform projects like melonDS. Homebrew, the primary way most people install the dependencies needed (rather unnecessarily as far as I can tell) goes out of its way to build packages targeting the macOS version you are running, rather than the one targeted by the project they're packaging itself. This means they won't work on any older version.
> 

That's clear and that's why user prefer .app that have all dependencies included instead of making it dependent on Homebrew. 

> The most feasible way to make a 10.13 build would be for me to install it in a virtual machine, build all the dependencies from source and then build melonDS, it's not really difficult for me to do, but it's quite a time sink to support an OS that is no longer officially supported by Apple with a very small remaining user base.

Apple products (Mac devices) generally have a small market share worldwide and I think just because it doesn't have a small market share, you shouldn't refuse support.

Apple products (Mac devices) generally have a small market share worldwide, and I think just because the market share is small, you should not refuse support.

In this particular case, I would be very happy if you would support not only macOS 10.13, but also an older macOS version. Preferably if it goes from macOS 10.4 (Mac OS X Tiger). because I own many Mac products that only support Mac OS X Tiger to macOS High Sierra.

**Comment by RayyanAnsari** [comment]
> you should not refuse support.

As said, it's just too impractical to support these old versions which Apple, Homebrew and GitHub Actions don't support themselves.

> I own many Mac products that only support Mac OS X Tiger to macOS High Sierra.

Hackintosh? Or even better, install a Linux distro :P

**Comment by xfrisakbaeun** [comment]
> Hackintosh? Or even better, install a Linux distro :P

I am just a normal user who likes to just load an .app and double click to start the software, dependencies or other things should not be seen by the user. This is one of the reasons why I like Apple products very much, which is of course also due to the late founder (Steve Jobs) partly.
 
Hackintosh or installing a Linux distro I do not like, because then the design is completely different, I have to look for unnecessary information on how to do exactly that and generally the Mac feeling is lost, there are several reasons why I fundamentally reject such things, do not be angry.

**Comment by nadiaholmquist** [comment]
Well, sorry. In that case there's not much we're able to do. All I have is machines running Monterey and the earliest we can easily get access to is 10.15.

**Comment by RSDuck** [comment]
Closed because of the reasons mentioned during the conversation. There doesn't seem to be a practical solution for this.
