### ISSUE TITLE
Saving custom DNS server

### ISSUE THREAD

**Issue by Mattlau04** [Arisotura/melonDS#1468]
It would be nice to be able to set the DNS server that MelonAP uses to something static, and then keep it saved so that it stays that way.
Currently, it seems to switch back to "Auto-obtain DNS" whenever the emulator is restarted, which makes using things like [Kaeru WFC](https://kaeru.world/projects/wfc) quite cumbersome

My suggestion is therefore that either changes to MelonAP are actually saved so they aren't lost at emulator restart.
This could also be accomplished with a new option in melonDS that sets the DNS server's address to a specified static one automatically when MelonAP is initialised

**Comment by Mattlau04** [comment]
I tried using extrernal BIOS/firmware files and now it saves the changes i make to my APs
However this would still be a pretty nice feature to have without needing the external BIOS/Firmware

**Comment by nadiaholmquist** [comment]
Can you test a dev build? I'm fairly sure the settings not being saved has been fixed but I may be remembering wrong.

Re: specifying a specific DNS server, I've been working on this but it turns out to be more annoying than one might expect it to be with the library we use for indirect mode. I want to have this feature in the next release though if possible.

**Comment by Mattlau04** [comment]
I couldn't manage to build from source, and i couldn't find a precompiled dev build to test :/

**Comment by Mattlau04** [comment]
Looks like it was indeed fixed in the dev build, sorry for the bother ^^
