### ISSUE TITLE
Add high level bios emulation

### ISSUE THREAD

**Issue by TheCoder3156** [Arisotura/melonDS#367]
Would it be possible to add this? It’s not possible for some people to get the bios9 and 7 for people with a dsi without pirating. Thanks!

**Comment by Arisotura** [comment]
yeah that'd be a good thing to add

**Comment by xperia64** [comment]
I would like to point out that DraStic ships a free drop-in BIOS replacement under a fairly liberal license. It isn't perfect, and obviously doesn't include any keys, but I've tested it with MelonDS 0.8.2, and it seems to be enough to boot games fine.

These do not replace firmware.bin, and there's obviously some weirdness if a blank firmware.bin is provided (such as touch not working due to lack of calibration), but games boot otherwise without the need of real bios dumps.

[drastic_bios.zip](https://github.com/Arisotura/melonDS/files/3366514/drastic_bios.zip)

**Comment by Arisotura** [comment]
generating a firmware would be easy enough (but it wouldn't be bootable)

not sure about the BIOS thing, I need to audit the DraStic BIOS. I don't want to end up with a billion bug reports stemming from a buggy BIOS replacement.

**Comment by TheCoder3156** [comment]
Maybe we could get desmume to relicense their bios code under GPLv2 or later so we could use it.

**Comment by TheCoder3156** [comment]
There are only two contributors so it might be easy to get permission.

**Comment by Arisotura** [comment]
DeSmuME doesn't have a full-fledged alternate BIOS. they set up a minimalistic IRQ handler, and they handle the SWI calls via HLE.

which has its set of issues (for example the decompression functions that use callbacks, ...)

**Comment by FrostKnight** [comment]
If it really is licensed under a free license, then its good till you get a better implementation.
Still a bit puzzled as to what website you found it in, but meh... w/e 
Hope you guys are working on an alternate bios though in the future. 
And yeah, you don't want a buggy replacement. Wisdom! :)

**Comment by WaluigiWare64** [comment]
wrong PR :P

**Comment by FrostKnight** [comment]
whoops... my bad.

**Comment by Arisotura** [comment]
done!
