### ISSUE TITLE
Resampling(?) issue in Linux with Alsa (baaad crackling)

### ISSUE THREAD

**Issue by wyatt8740** [Arisotura/melonDS#373]
I'm using the latest git version, although the following also happens in 0.7.3.

When I run any game, or even just enter the bios menu, I get horrid crackling in my speakers. While playing a game, sometimes the audio will momentarily mostly stop crackling and become audible, but the rest of the time it is pretty much just noise. It slides in and out of clarity.

Oddly, when I did something silly and changed `whatIwant.freq = 47340;` to `48000`, the crackling mostly went away (though there was still a little bit present, it didn't "desynchronize"), at the cost of playing too fast.
Thus, my guess is that either SDL or your software isn't resampling very well, or else that my hardware has issues (unlikely, because it works fine with absolutely everything else).

The chipset is a realtek ALC892, by the way (Intel PCH). I am using Alsa + dmix without pulseaudio.

I've attached an approximately 30 second sample where you can hear what I mean. I am getting consistent 60fps. My hardware supports 48000hz sampling, of course, but not 47340.
[melonds-sampling.zip](https://github.com/Arisotura/melonDS/files/2800518/melonds-sampling.zip)

**Comment by wyatt8740** [comment]
I suppose it could be an SDL2 bug, as well, but I'm having a hard time finding any useful information on that front.

**Comment by Arisotura** [comment]
not too sure what to say about this one...

could blame melonDS for using a nonstandard sampling frequency

but could also blame your driver for claiming to support that frequency when it's doing a terrible job at it

so...

considering how driver bugs usually go, I might have to work around this. blarg

for reference: the sampling rate of 47340Hz was chosen because 1024 samples at that rate are exactly 710 samples at the output rate of the melonDS core (which is, ideally, 32823.6328125Hz. the non-integer frequency is shit to work with, you figure).

**Comment by wyatt8740** [comment]
It could be my alsa drivers, for sure.

This was a system I set up years ago without pulseaudio back when I had a Sound Blaster Audigy ZS. I can try changing the internal sampling frequency in my alsa config. I still somewhat suspect it's an SDL resampler bug.

**Comment by wyatt8740** [comment]
Update again: Going to pick up an old Sound Blaster Audigy 2 ZS that I left with my parents when I moved out. Will try it there and see if it's any different.

**Comment by wyatt8740** [comment]
Looks like it was because I had at some point told ALSA that my sound card should output audio with a 44.1khz sample rate.
works better at 48khz (not always 100% perfect, but only slight crackling occasionally.)
