### ISSUE TITLE
!! SOUND FIFO OVERFLOW when pausing

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#502]
Occasionally there is some audio corruption accompanied with a !! SOUND FIFO OVERFLOW in the console.

Windows 10 (1903)
i5-4200U
AMD Radeon HD 8750m

**Comment by nathanielcwm** [comment]
Actually seems like it mostly shows up when pausing or just starting up the game
The audio corruption could possibly be because of dropping frames.

**Comment by nathanielcwm** [comment]
Also the framerate drops heavily while it's saving

**Comment by nathanielcwm** [comment]
It seems to happen occasionally during normal gameplay too.
Also when loading.

**Comment by Arisotura** [comment]
pls keep it to one thing per issue you open, it makes it easier to manage

anyway this is known and has been going on since forever, it's just apparent because there's logging code in the latest revisions. basically, every once in a while the sound FIFO overflows because the emu core is running slightly faster than the audio output stream thing. this is where audio issues in melonDS stem from.

**Comment by Arisotura** [comment]
I removed the logging for it (and dealt with it more elegantly). also, from now on, overflow/underflow is going to be considered normal unless audio sync is enabled.
