### ISSUE TITLE
BIOS files not found when ironically in said firmware file. (REAL TIME CORRUPTOR)

### ISSUE THREAD

**Issue by RadsammyT** [Arisotura/melonDS#515]
Posting this because there was no other solution i can think of.
When launching the emulator just from the executable w/ or w/o vanguard (corruption client), it errors saying that I am missing BIOS files, I have them all and it is right in this [gif](https://i.imgur.com/LINLnKJ.gifv)

any help?

**Comment by InstallGentoo11** [comment]
You don't have what the emulator is asking of you.

**Comment by RadsammyT** [comment]
> You don't have what the emulator is asking of you.

Look in the link.

**Comment by RadsammyT** [comment]
### I am a fucking idiot.

bios7 and 9 were ROM files, not BIN files. I simply renamed them into BIN files.

**Comment by Brian151** [comment]
to be fair, this is the kind of technicality that programs shouldn't be having an issue with.

there's always the possibility a dump of the BIOS does not have the same file name or extension
and let's not forget custom firmware...

it's like all these image editors that won't open a JPG/PNG that isn't given a JPG/PNG extension. validation really should be performed on the contents of files...

and something like BIOS files in an emulator really should be able to be re-named or specified at the user's discretion.

just my thoughts on this

[late reply because i am not entirely focused on my github notifications, especially from this repo]

**Comment by Arisotura** [comment]
yeah.

letting users pick their BIOS files is in the TODO list. for now those are just hardcoded because I know this will be revamped.
