### ISSUE TITLE
Forward speed is not right

### ISSUE THREAD

**Issue by SenseiLeRoof** [Arisotura/melonDS#537]
Gameplay is fast-forwarded by default. If I hold down the fast-forward button (currently RT) gameplay slows to normal speed. Fast-forward toggle does nothing.

**Comment by Arisotura** [comment]
wat

have you tried mapping the fast-forward button to another button or key?

**Comment by SenseiLeRoof** [comment]
Changed to LT, that seemed to fix it. Changed back to RT and it stayed fixed, so I think I'm in the clear.

**Comment by Arisotura** [comment]
when mapping, melonDS might have caught the 'trigger release' movement instead of 'trigger press', which would have confused its trigger detection code (basically, triggers are recognized as axis controls with a different range; melonDS compares all axis readings against the 'resting position values' it got and uses both to determine what the control is and in which direction it was operated)
