### ISSUE TITLE
graphical corruption

### ISSUE THREAD

**Issue by Liger0** [Arisotura/melonDS#604]
I tried all NDS pokemon games and there is severe graphical corruption everywhere in the open world.
![DIAMOND TOP](https://user-images.githubusercontent.com/20385116/80007327-64ef0b00-84c6-11ea-9005-9552347c7e34.png)
![HG TOP](https://user-images.githubusercontent.com/20385116/80007331-6587a180-84c6-11ea-9357-10d8b2a0e597.png)

**Comment by RSDuck** [comment]
you're probably using the OpenGL renderer, this does not occur with the more accurate software renderer.

see #458

**Comment by Liger0** [comment]
Indeed, you're right. I'll close this then if it isn't of any hint over the #458

**Comment by Liger0** [comment]
By the way, on Desmume I don't have those issues using OpeGL, just in case this could be of any use. (if anything on desmume I *have to* use OpenGL because the others don't work correctly.

**Comment by RSDuck** [comment]
in theory a software renderer can be as accurate as hardware while renderer using the GPU can likely not, simply because it's flexibilty ends at some point. Both the software renderer and the OpenGL renderer of desmume are not very accurate, but the OpenGL renderer is faster, so they implemented some hacks there to circumvent these issues. At the otherhand melonDS's software renderer doesn't show this issue because it is a lot more accurate (though not pixel perfect yet) and it's OpenGL renderer does not have the hack necessary implemented.
