### ISSUE TITLE
Melonds crashes when opening .ml save file

### ISSUE THREAD

**Issue by AbsenceFlintIvy** [Arisotura/melonDS#760]
Game used: Pokemon White
C-Gear was on
DS Mode
3D Renderer: OpenGL 6x native with polygon splitting
Error: Segmentation fault (core dumped)

**Comment by RSDuck** [comment]
In any case, this shouldn't crash the emulator, but was the save made with a previous version?

**Comment by AbsenceFlintIvy** [comment]
Yes, it was.

**Comment by RSDuck** [comment]
savestates aren't compatible between versions (because they contain internal data which may change).

ah yes, you did report this bug: https://github.com/Arisotura/melonDS/issues/739

can you give me your savestate? There's a hack I can apply to unfreeze those savefiles, then you can properly save and migrate to the new version. Fortunately we made some progress in finding out what's the cause of this bug, hopefully soon it won't be eable to appear anymore.

**Comment by AbsenceFlintIvy** [comment]
Here, thank you for helping me! https://drive.google.com/file/d/10xV8VL3-deh1c3MkUku9NAsA47DtLky6/view?usp=sharing

**Comment by RSDuck** [comment]
did you use 0.8.3 to make the savestate? And are you sure the game freezes when you try to save?

**Comment by AbsenceFlintIvy** [comment]
I used 0.8.3 to create the savestate, and I cannot load it in 0.9.

**Comment by RSDuck** [comment]
yes, but can you open it in 0.8.3 and then save (in the game)?

**Comment by AbsenceFlintIvy** [comment]
Oh, give me a second to do that, I'm in an online class right now.

**Comment by AbsenceFlintIvy** [comment]
Thanks for helping!

**Comment by RSDuck** [comment]
I thought your game would always freeze when you try to save. That scared me, because I couldn't find any signs of this in the savestate you sent me, so there could have been another reason for those freezes besides the one we've found.

But yeah, saving in game is always prefered over savestates (and necessary when switching from one version to another) because the savestate format is unstable.

**Comment by SwishyBro473** [comment]
Hey RSDuck sorry to bother but im having the same problem. Whats the hack to unfreeze save files? thanks!

**Comment by RSDuck** [comment]
it's super unstraightforward, you need to hack the savestate to set a wifi registers to a different value

**Comment by SwishyBro473** [comment]
oh ok, and i assume your to busy to do so

**Comment by RSDuck** [comment]
don't worry, I'm the one who wanted to fix this already months ago, but never did. I need to your savestate to apply this fix.

**Comment by SwishyBro473** [comment]
Thank you so much! it would make my day 
https://drive.google.com/file/d/1U2Jw_RXfHgjJ4uYpqGCLPlIxGeV-KIMg/view?usp=sharing

**Comment by SwishyBro473** [comment]
Tell me when its done the other guy got it without you sending anything? so not sure if you sent it in a specific way or not

**Comment by RSDuck** [comment]
[Pokemon - White Version 2 (USA, Europe) (NDSi Enhanced).zip](https://github.com/Arisotura/melonDS/files/5745447/Pokemon.-.White.Version.2.USA.Europe.NDSi.Enhanced.zip)

the other person had a different problem afterall. Not enabling the C-gear is a workaround which prevents freezes like this. Also always save in game reguarly.

**Comment by SwishyBro473** [comment]
oh also ok ill see if it works!

**Comment by SwishyBro473** [comment]
it worked but he asked me to save and it says 
![image](https://user-images.githubusercontent.com/76667808/103182074-22ec4500-485d-11eb-8a5f-4ddb7fc7f624.png)

**Comment by SwishyBro473** [comment]
any fix for this?

**Comment by RSDuck** [comment]
idk, could be possible that something else in the savestate is broken because the game was in a weird state for too long. Unfortunately the only thing I can tell you is to play from your latest regularr savefile.

**Comment by SwishyBro473** [comment]
I just Figured it out! thank you so much!
