### ISSUE TITLE
The title screen of The Daring Game For Girls flickers with the software renderer 

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#869]
This is strange. It only seems to happen with the software renderer and not with OpenGL.

![Capture](https://user-images.githubusercontent.com/68873449/102712303-32770580-4314-11eb-838f-aeec6d4cb90a.PNG)

**Comment by Arisotura** [comment]
removing the OpenGL label, that issue is the opposite of the typical OpenGL issue

(btw, interesting)

**Comment by Arisotura** [comment]
nah. the flickering is normal -- this renders 3D on both screens. due to derpiness in the DS hardware, the 2D and 3D engines output slightly different colors (the 15bit colors are converted to 18bit in different ways), which results in this flickering. it also happens on hardware, but the high LCD response time attenuates it so you don't notice it unless you pay close attention.

it might not be happening on OpenGL because that renderer is not quite accurate in how it converts colors.

**Comment by Tiberius1437** [comment]
Shouldn't this be open as an OpenGL issue then? If it isn't doing something that's supposed to happen on real hardware?

**Comment by poudink** [comment]
The OpenGL renderer cannot be 100% accurate, so I believe the reasoning is that if it looks normal then it's fine.
