### ISSUE TITLE
Tori's head is sometimes transparent in Victorious - Hollywood Arts Debut (USA) (En,Fr,De,Es,It) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#902]
I don't mean to be impatient but are y'all workin' on any of the issues I'm reporting or are you too busy? Anyway when Tori leans to the right you can see the wall through her head.

Software

![Capture](https://user-images.githubusercontent.com/68873449/103139237-541a2780-472e-11eb-8c89-5043ee9a69a4.PNG)

OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/103139243-5c726280-472e-11eb-8eb2-a87bc5fdfed5.PNG)

**Comment by RSDuck** [comment]
> I don't mean to be impatient but are y'all workin' on any of the issues I'm reporting or are you too busy? Anyway when Tori leans to the right you can see the wall through her head.

the OpenGL renderer will never be perfect because it's just not possible accurately replicate the quirky DS GPU with a modern GPU. That doesn't mean we aren't thinking possible solutions as some issues are definitely completely fixable, but for other's there are only workarounds and hacks we could try.

**Comment by poudink** [comment]
fixed by https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241
