### ISSUE TITLE
(Feature Request) "Force Integer Scaling" option

### ISSUE THREAD

**Issue by yuriks** [Arisotura/melonDS#91]
Would be extremely helpful to have an option to restrict scaling to integer ratios. A 1x window is very small on my monitor, and larger sizes have distorted pixels due to the lack of filtering or rounding of the scaling ratio.

For now I'm using [an utility](http://www.brianapps.net/sizer4/) to resize the melonDS window to a specific size which gives me an exact 2x scaling, but it would be great to make this unnecessary.

**Comment by Nadia-h** [comment]
Until this is implemented you can edit the exact window size in melonDS.ini.
The size you want is 512x768.

**Comment by StapleButter** [comment]
Relatedly, something I noticed on the DS capture tool: when resizing the window, the size is temporarily shown in the title bar. This may be convenient to have in melonDS.

**Comment by Arisotura** [comment]
latest versions have a menu for setting 1x/2x/... window sizes, is that what you wanted? or did you mean locking the window to integer sizes?

**Comment by steventylerseanherr** [comment]
im not yuriks
but the way the force integer scaling option works on mgba works would be nice
instead of melonds doing what it does now with scaling the screen up till it hits the top and bottom of the window
it would scale it up as big as it can and then add black bars on all four sides for the rest of the screen
![image](https://user-images.githubusercontent.com/48705919/68274355-e517d600-0036-11ea-992d-e9f0946281bb.png)

**Comment by RSDuck** [comment]
this has been in melonDS for a while now
